### PR TITLE
Only vector features can be shared in permalink

### LINKED ISSUE #938: Share map AGS Map Service
**Describe the bug**
When sharemap with selected object on AGS Map Service the map is blank. 
**To Reproduce**
[https://www.malardalskartan.se/origo/v2.2.0/test.html#layers=topowebbkartan_nedtonad/v/1/s/0,isbanor/v/1/s/0&center=153470,6612205&zoom=7.6155244561302435&feature=isbanor.2690&map=test](https://www.malardalskartan.se/origo/v2.2.0/test.html#layers=topowebbkartan_nedtonad/v/1/s/0,isbanor/v/1/s/0&center=153470,6612205&zoom=7.6155244561302435&feature=isbanor.2690&map=test)

**Expected behavior**
There should be a map present and init zoom to selected object.

### PR DESCRIPTION
**Pull request by jokd**
Fixes #938

### CODE REVIEW

File: src/viewer.js [hunk 1]
```diff
@@ -411,11 +411,12 @@ const Viewer = function Viewer(targetOption, options = {}) {
         const featureId = urlParams.feature;
         const layerName = featureId.split('.')[0];
         const layer = getLayer(layerName);
-        const clusterSource = layer.getSource().source;
+        const layer2 = getLayer('intressepunkt');
```
Comment (mulfvik) [inline src/viewer.js:414]: ?

Comment (jokd) [reply src/viewer.js]: That line maybe ain't necessary....removed!
